# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/shared", create: true

 
  config.vm.define "kdc" do |server|
    server.vm.provider "virtualbox" do |vb|
       vb.customize ["modifyvm", :id, "--cpus", "2"]
       vb.name = "kdc"
       vb.memory = 1024
    end
    server.vm.hostname = "kdc.foobar.com"
    server.vm.network :private_network, ip: "192.168.22.22"
    server.vm.provision :shell, path: "config-kdc", args: ENV['ARGS']
    end

end
