# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/shared", create: true
  config.vm.network :forwarded_port, guest:22, host:2227 
  
  config.vm.define "node0" do |server|
    server.vm.provider "virtualbox" do |vb|
       vb.customize ["modifyvm", :id, "--cpus", "1"]
       vb.name = "node0"
       vb.memory = 512
    end
    server.vm.hostname = "node0.foobar.com"
    server.vm.network :private_network, ip: "192.168.22.27"
    server.vm.network :forwarded_port, guest:22, host:2227   
    end

end
