# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/shared", create: true
  
  config.vm.define "nodeb" do |server|
    server.vm.provider "virtualbox" do |vb|
       vb.customize ["modifyvm", :id, "--cpus", "1"]
       vb.name = "nodeb"
       vb.memory = 512
    end
    server.vm.hostname = "nodeb.foobar.com"
    server.vm.network :private_network, ip: "192.168.222.20"
    server.vm.provision :shell, path: "config-nodeb", args: ENV['ARGS']
    
    end

end
