#!/usr/bin/env bash

set -e
set -x


function config_hosts(){
  echo "configure /etc/hosts..."
  echo "192.168.222.20 nodeb.foobar.com nodeb"   >> /etc/hosts
  echo "192.168.222.30 nodec.foobar.com nodec"   >> /etc/hosts

}

function install_mongodenterprise(){
  echo "install mongodb enterprise 3.4"
  cp /shared/mongodb-enterprise.repo /etc/yum.repos.d/mongodb-enterprise.repo
  yum install -y mongodb-enterprise
}

function create_db_path(){
  mkdir -p /data/nodea
  chown mongod /data/nodea
  mkdir -p /data/nodea/logs
  chown mongod /data/nodea
}

config_hosts
install_mongodenterprise
create_db_path
echo "DONE"
