# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/shared", create: true
  config.vm.network :forwarded_port, guest: 22, host: 2235 
  
  config.vm.define "agents" do |server|
    server.vm.provider "virtualbox" do |vb|
       vb.customize ["modifyvm", :id, "--cpus", "1"]
       vb.name = "agents"
       vb.memory = 512
    end
    server.vm.hostname = "agents.foobar.com"
    server.vm.network :private_network, ip: "192.168.22.26"

    
    end

end
