#!/usr/bin/env bash

set -e
set -x


function config_hosts(){
  echo "configure /etc/hosts..."
  echo "192.168.222.20 nodeb.foobar.com nodeb"   >> /etc/hosts
  echo "192.168.222.10 nodea.foobar.com nodea"   >> /etc/hosts
  echo "192.168.22.24 opsmgr.foobar.com opsmgr"   >> /etc/hosts
  echo "192.168.22.26 agents.foobar.com agents"   >> /etc/hosts
}

function install_mongodenterprise(){
  echo "install mongodb enterprise 3.4"
  cp /shared/mongodb-enterprise.repo /etc/yum.repos.d/mongodb-enterprise.repo
  yum install -y mongodb-enterprise
}

function create_db_path(){
  mkdir -p /data/3nodes/nodec/logs
  chown mongod:mongod -R /data
}

function createReplicaSet(){
  sudo cp /shared/mongod.conf /data/3nodes/nodec/mongod.conf
  sudo chown mongod:mongod /data/3nodes/nodec/mongod.conf
  sudo chmod 400 /data/3nodes/nodec/mongod.conf
  sudo -u mongod mongod -f /data/3nodes/nodec/mongod.conf
}

config_hosts
install_mongodenterprise
create_db_path
createReplicaSet
echo "DONE"
