# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/shared", create: true
  
  config.vm.define "opsmgr" do |server|
    server.vm.provider "virtualbox" do |vb|
       vb.customize ["modifyvm", :id, "--cpus", "2"]
       vb.name = "opsmgr"
       vb.memory = 4096
    end
    server.vm.hostname = "opsmgr.foobar.com"
    server.vm.network :private_network, ip: "192.168.22.24"

    
    end

end
