#!/usr/bin/env bash

set -e
set -x


function config_hosts(){
  
  echo "configure /etc/hosts..."
  #KERBEROS BASIC CONFIG
  echo "192.168.22.22 kdc.foobar.com kdc"   >> /etc/hosts
  echo "192.168.22.23 kdc-client.foobar.com kdc-client"   >> /etc/hosts
  #KERBEROS OM INTEGRATION CONFIG
  echo "192.168.22.24 opsmgr.foobar.com opsmgr"   >> /etc/hosts
  echo "192.168.22.25 backup.foobar.com backup"   >> /etc/hosts
  echo "192.168.22.26 agents.foobar.com agents"   >> /etc/hosts
  echo "192.168.22.27 node0.foobar.com node0"   >> /etc/hosts
  echo "192.168.22.28 node1.foobar.com node1"   >> /etc/hosts
  echo "192.168.22.29 node2.foobar.com node2"   >> /etc/hosts
}

function install_ntp(){
  echo "INSTALL NTP"
  sudo yum -y install ntp
  sudo ntpdate 0.rhel.pool.ntp.org
  sudo systemctl start  ntpd.service
  sudo systemctl enable ntpd.service
}

function install_kerberos_client(){
  # install kerberos client and libs
  sudo yum -y install krb5-workstation
  # copy paste the content of krb5.conf file 4 -rw-r--r--.  1 root root      583 Mar 30 15:50 krb5.conf
  sudo cp /shared/krb5.conf /etc/krb5.conf
  sudo chown root:root /etc/krb5.conf
  sudo chmod 644 /etc/krb5.conf
}

config_hosts
install_ntp
install_kerberos_client

echo "DONE"