# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.box_check_update = false
  config.vm.synced_folder "shared/", "/shared", create: true
  #config.vm.provision "file", source: "../kdc/shared/kdc-client.foobar.com.keytab", destination: "/shared/"

  config.vm.define "kclient" do |server|
    server.vm.provider "virtualbox" do |vb|
       vb.customize ["modifyvm", :id, "--cpus", "1"]
       vb.name = "kclient"
       vb.memory = 512
    end
    server.vm.hostname = "kdc-client.foobar.com"
    server.vm.network :private_network, ip: "192.168.22.23"
    server.vm.provision :shell, path: "./config-kdc-client", args: ENV['ARGS']
    end

end
